# application-DEV.yml
variable:
  profiles : DEV

server:
  address: 'localhost'
  port: 8080

spring:
  application:
    name: MCC
  boot:
    admin:
      notify:
        line:
          enabled: true
          channelSecret: '5dc15d1fa976b8c40654c1d0db71cf6e'
          channelToken: '6K5NLaEmALTry4msSXSbBaNMuSydHIZD9Z0ToApTwFeHiszr4cNAO8A/Jgmo4QrxV6gBrcRlGCZhvTg72YAj9Izc5Mibp37VKGGL1UtU9Ai15OkZFqZgPfv2iJQaG4IfaTyaEim1t96s5H+mipVXeAdB04t89/1O/w1cDnyilFU='

  kafka:
    consumer:
      bootstrap-servers: 'localhost:29092,localhost:29093,localhost:29094'
      group-id: 'notification-center'
    producer:
      bootstrap-servers: 'localhost:29092,localhost:29093,localhost:29094'
      group-id: 'notification-center'
    streams:
      application-id: 'notification-center'
      bootstrap-servers: 'localhost:29092,localhost:29093,localhost:29094'
      replication-factor: 2
      #state-dir: '/tmp/kafka-streams-2'




  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'wisttonyyang@gmail.com'
    password: 'avqazsyqmifcukgs'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
